In [23]:
with open('poems.txt','r') as f:
    data=f.read().split('\n')

In [24]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing import text
from tensorflow.keras.preprocessing.text import Tokenizer

In [25]:
tokenizer=Tokenizer(oov_token='<nothing>')
tokenizer.fit_on_texts(data)

In [26]:
tokenizer.word_index

{'<nothing>': 1,
 'the': 2,
 'and': 3,
 'to': 4,
 'his': 5,
 'in': 6,
 'of': 7,
 'a': 8,
 'her': 9,
 'she': 10,
 'that': 11,
 'he': 12,
 'with': 13,
 'not': 14,
 'my': 15,
 'is': 16,
 'but': 17,
 'i': 18,
 'so': 19,
 'for': 20,
 'as': 21,
 'thou': 22,
 'it': 23,
 'love': 24,
 'be': 25,
 'their': 26,
 'all': 27,
 "'": 28,
 'him': 29,
 'by': 30,
 'on': 31,
 'this': 32,
 'thy': 33,
 'me': 34,
 'or': 35,
 'like': 36,
 'did': 37,
 'what': 38,
 'they': 39,
 'doth': 40,
 'now': 41,
 'from': 42,
 'was': 43,
 'no': 44,
 'thee': 45,
 'which': 46,
 'eyes': 47,
 'are': 48,
 'them': 49,
 'one': 50,
 'at': 51,
 'will': 52,
 'shall': 53,
 'would': 54,
 'yet': 55,
 'whose': 56,
 'heart': 57,
 'where': 58,
 'more': 59,
 'when': 60,
 'being': 61,
 'have': 62,
 'if': 63,
 'hath': 64,
 'o': 65,
 'were': 66,
 'fair': 67,
 'then': 68,
 'upon': 69,
 'sweet': 70,
 'do': 71,
 'you': 72,
 'beauty': 73,
 'had': 74,
 'lips': 75,
 'eye': 76,
 'never': 77,
 'mine': 78,
 'who': 79,
 'face': 80,
 'nor': 81,
 'should'

In [27]:
input_sequences=tokenizer.texts_to_sequences(data)
input_sequences

[[42, 249, 8, 507, 56, 1287, 508, 1288],
 [8, 1289, 744, 42, 8, 1290, 1291],
 [15, 745, 4, 746, 32, 327, 280, 1292],
 [3, 165, 18, 747, 4, 748, 2, 250, 1293, 328],
 [281, 166, 1294, 8, 749, 329, 121, 122],
 [1295, 7, 1296, 750, 751, 8, 282],
 [1297, 9, 167, 13, 1298, 132, 3, 208],
 [],
 [69, 9, 183, 8, 1299, 1300, 7, 1301],
 [46, 1302, 9, 509, 42, 2, 100],
 [283, 2, 209, 210, 399, 184, 23, 185],
 [2, 1303, 7, 73, 510, 3, 186],
 [168, 74, 14, 1304, 27, 11, 251, 400],
 [81, 251, 27, 1305, 17, 511, 7, 330, 512, 401],
 [92, 73, 1306, 106, 1307, 7, 1308, 252],
 [],
 [402, 37, 10, 1309, 9, 1310, 4, 9, 752],
 [46, 31, 23, 74, 1311, 753],
 [1312, 2, 754, 1313, 6, 2, 1314],
 [11, 1315, 150, 74, 1316, 6, 93],
 [3, 211, 1317, 38, 755, 23, 756],
 [21, 211, 757, 1318, 150],
 [6, 758, 7, 27, 1319, 151, 169, 3, 403],
 [],
 [331, 9, 759, 47, 26, 1320, 760],
 [21, 39, 37, 513, 4, 2, 1321, 1322],
 [184, 1323, 26, 112, 761, 48, 404],
 [4, 2, 1324, 152, 331, 39, 71, 762],
 [26, 405, 284, 31, 332, 26, 763,

In [28]:
print(len(input_sequences))

1991


In [29]:
# Remove all empty sequences
sequences = [seq for seq in input_sequences if len(seq) > 0]

In [30]:
sequences

[[42, 249, 8, 507, 56, 1287, 508, 1288],
 [8, 1289, 744, 42, 8, 1290, 1291],
 [15, 745, 4, 746, 32, 327, 280, 1292],
 [3, 165, 18, 747, 4, 748, 2, 250, 1293, 328],
 [281, 166, 1294, 8, 749, 329, 121, 122],
 [1295, 7, 1296, 750, 751, 8, 282],
 [1297, 9, 167, 13, 1298, 132, 3, 208],
 [69, 9, 183, 8, 1299, 1300, 7, 1301],
 [46, 1302, 9, 509, 42, 2, 100],
 [283, 2, 209, 210, 399, 184, 23, 185],
 [2, 1303, 7, 73, 510, 3, 186],
 [168, 74, 14, 1304, 27, 11, 251, 400],
 [81, 251, 27, 1305, 17, 511, 7, 330, 512, 401],
 [92, 73, 1306, 106, 1307, 7, 1308, 252],
 [402, 37, 10, 1309, 9, 1310, 4, 9, 752],
 [46, 31, 23, 74, 1311, 753],
 [1312, 2, 754, 1313, 6, 2, 1314],
 [11, 1315, 150, 74, 1316, 6, 93],
 [3, 211, 1317, 38, 755, 23, 756],
 [21, 211, 757, 1318, 150],
 [6, 758, 7, 27, 1319, 151, 169, 3, 403],
 [331, 9, 759, 47, 26, 1320, 760],
 [21, 39, 37, 513, 4, 2, 1321, 1322],
 [184, 1323, 26, 112, 761, 48, 404],
 [4, 2, 1324, 152, 331, 39, 71, 762],
 [26, 405, 284, 31, 332, 26, 763, 253],
 [4, 123

In [33]:
max_len=max([len(x) for x in inputs])

In [32]:
inputs=[]
for seq in sequences:
    for i in range(1,len(seq)):
        inputs.append(seq[:i+1])
print(inputs)

[[42, 249], [42, 249, 8], [42, 249, 8, 507], [42, 249, 8, 507, 56], [42, 249, 8, 507, 56, 1287], [42, 249, 8, 507, 56, 1287, 508], [42, 249, 8, 507, 56, 1287, 508, 1288], [8, 1289], [8, 1289, 744], [8, 1289, 744, 42], [8, 1289, 744, 42, 8], [8, 1289, 744, 42, 8, 1290], [8, 1289, 744, 42, 8, 1290, 1291], [15, 745], [15, 745, 4], [15, 745, 4, 746], [15, 745, 4, 746, 32], [15, 745, 4, 746, 32, 327], [15, 745, 4, 746, 32, 327, 280], [15, 745, 4, 746, 32, 327, 280, 1292], [3, 165], [3, 165, 18], [3, 165, 18, 747], [3, 165, 18, 747, 4], [3, 165, 18, 747, 4, 748], [3, 165, 18, 747, 4, 748, 2], [3, 165, 18, 747, 4, 748, 2, 250], [3, 165, 18, 747, 4, 748, 2, 250, 1293], [3, 165, 18, 747, 4, 748, 2, 250, 1293, 328], [281, 166], [281, 166, 1294], [281, 166, 1294, 8], [281, 166, 1294, 8, 749], [281, 166, 1294, 8, 749, 329], [281, 166, 1294, 8, 749, 329, 121], [281, 166, 1294, 8, 749, 329, 121, 122], [1295, 7], [1295, 7, 1296], [1295, 7, 1296, 750], [1295, 7, 1296, 750, 751], [1295, 7, 1296, 750, 7

In [35]:
#Padding Sequence
from tensorflow.keras.utils import pad_sequences
padded_sequences=pad_sequences(inputs,padding='pre',maxlen=max_len)

In [36]:
padded_sequences

array([[   0,    0,    0, ...,    0,   42,  249],
       [   0,    0,    0, ...,   42,  249,    8],
       [   0,    0,    0, ...,  249,    8,  507],
       ...,
       [   0,    0,    0, ...,    8, 3435,   52],
       [   0,    0,    0, ..., 3435,   52,   14],
       [   0,    0,    0, ...,   52,   14, 1171]])

In [37]:
X=padded_sequences[:,:-1]
y=padded_sequences[:,-1]

In [38]:
X

array([[   0,    0,    0, ...,    0,    0,   42],
       [   0,    0,    0, ...,    0,   42,  249],
       [   0,    0,    0, ...,   42,  249,    8],
       ...,
       [   0,    0,    0, ..., 1129,    8, 3435],
       [   0,    0,    0, ...,    8, 3435,   52],
       [   0,    0,    0, ..., 3435,   52,   14]])

In [41]:
max(tokenizer.word_index.values())

3435

In [42]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=3436)

In [43]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
X.shape

(11820, 12)

In [48]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding,Dense,LSTM
model=Sequential()
model.add(Embedding(3436,output_dim=100,input_shape=(12,)))
model.add(LSTM(150))
model.add(Dense(3436,activation='softmax'))
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [50]:
model.fit(X,y,epochs=100)

Epoch 1/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.1376 - loss: 4.5209
Epoch 2/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.1755 - loss: 4.2642
Epoch 3/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.2164 - loss: 4.0128
Epoch 4/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.2671 - loss: 3.7849
Epoch 5/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.3134 - loss: 3.5496
Epoch 6/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.3647 - loss: 3.3057
Epoch 7/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.4073 - loss: 3.1193
Epoch 8/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.4484 - loss: 2.8839
Epoch 9/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.4876 - loss: 2.7178
Epoch 10/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.5341 - loss: 2.4595
Epoch 11/100
370/370 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.5718 - loss: 2.2815
Epoch 12/100
370/370 ━━━━━━━━━━━━━━━━━━━━

In [62]:
import time
text="moon"
loop=5
for i in range(loop):
    input_=tokenizer.texts_to_sequences([text])[0]
    padded_input=pad_sequences([input_],maxlen=13,padding='pre')
    pos = np.argmax(model.predict(padded_input))
    for word,index in tokenizer.word_index.items():
        if index == pos:
          text = text + " " + word
          print(text)
          time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
moon make
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
moon make them
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
moon make them chant
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
moon make them chant it
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
moon make them chant it lustily
